### PR TITLE
Feat/workflow generate

### PR DESCRIPTION
**Pull request by relent0r**
This PR adds the generate work flow that generates the requires json files for wiki creation.

Uses a similar design as the default FAF file generation.

Note : Dependency on PR that adds total-mayhem blueprint names to the spookydb whitelist for the cleaner

Test : Requires to be merged into the develop branch in order to manually trigger.

### CODE REVIEW

**Comment by Garanas** [comment]
Is this pull request aiming to solve #2 ?

**Comment by relent0r** [comment]
> Is this pull request aiming to solve #2 ?

Initially I thought it would, then I realised that the issue is talking about the icons which I haven't done.

**Comment by Garanas** [comment]
I'm confused though, the issue is about generating the wiki, not about Spooky DB 😄 ! There is no need to generate a JSON file, for example.

**Comment by relent0r** [comment]
> I'm confused though, the issue is about generating the wiki, not about Spooky DB 😄 ! There is no need to generate a JSON file, for example.

omg I thought the json files that the tools from spookydb produces is used for the wiki 0_0 well I got to read some python so wasn't a complete waste.

**Pull request closed without merging**
