### PR TITLE
Fix a muzzle of the mighty Thaez-Atha

### PR DESCRIPTION
**Pull request by Uveso**
https://github.com/FAForever/fa-total-mayhem/issues/16

grafik

thanks for @zhanghm18GIT for providing the patched lod0 file.

### CODE REVIEW

**Comment by Garanas** [comment]
This pull request also contains https://github.com/FAForever/fa-total-mayhem/pull/26, can you rebase it to not include https://github.com/FAForever/fa-total-mayhem/pull/27/commits/fcffccff57cdcfaf06554a44fbd0443a3f1a06eb ?

**Comment by Garanas** [comment]
And while you're at that - feel free to update the readme and add your name to the credits. You did work on this mod after all 😄 !

**Comment by zhanghm18GIT** [comment]
> This pull request also contains #26, can you rebase it to not include [fcffccf](https://github.com/FAForever/fa-total-mayhem/commit/fcffccff57cdcfaf06554a44fbd0443a3f1a06eb) ?
Thank you for your notice. But I don't know how to do that.

**Comment by Uveso** [comment]
Oh yes, at first I was thinking of making one PR for both, but then I split it up and forgot to remove it here.

And i feel free to not update the readme and don't add my name to the credits. :D :D :D
sorry, but what "readme" do you mean? "Bugfix by Uveso.txt" ? (we should rename that... )

**Comment by Garanas** [comment]
The primary readme that has a credit section:

image

**Review by Garanas — APPROVED** [review]

**Comment by Uveso** [comment]
Ah i see.

No, there is no need to add my name to this list.

**Pull request merged**
