### PR TITLE
Optimize self:GetBlueprint()

### PR DESCRIPTION
**Pull request by Uveso**
Replaced self:GetBlueprint() with self.Blueprint for improved performance.

### CODE REVIEW

**Comment by MrRowey** [comment]
Be aware nobody is maintaining this repo game team doesn't want the responsibility it was ment to be put in to archived mode, so I deleted all my Prs .

**Comment by Uveso** [comment]
well, then its up to us. :)

**Comment by MrRowey** [comment]
> well, then its up to us. :)

their no way way to uploaded this to the vault tho ?

**Comment by Garanas** [comment]
If I am not mistaken then @Uveso is the original author of the upload in the vault. Which means that he can update what is on the vault.

The original plan of this repository was to maintain the mod through the community, and not specifically through the game team. However, nobody can upload it to the vault because we're not Uveso 😄 . The idea was that there would be an extension of the FAForever API that would allow a GitHub Action to update the mod. That way we did not have to bother you all the time with a request to update it. But that idea is not implemented anytime soon. Hence the idea to archive this repository.

But if @Uveso is available to update the mod in the vault every now and then that is fine too.

**Comment by Uveso** [comment]
@Garanas 

Well, there is a slight problem: the FAF launcher can't upload the mod because it is too big.
The last time, I asked Brutus to upload the file directly to the server and update the database to the new version. :)

I was also asked not to upload too many versions of the mod, as it consumes a lot of disk space.

But this can be solved later.
First, I want to update the mod.

**Comment by MrRowey** [comment]
@Uveso ill reopen up what i did then and shoot it your way for review :)

**Pull request merged**
